<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>BJCP game</title>
        <link rel="stylesheet" href="assets/css/style.css?v=1">
        <link rel="icon" type="image/x-icon" href="assets/img/favicon.ico" />
    </head>
    <body>
        <div class="options" id="option-1">
        </div>
        <div class="options" id="option-2">
        </div>
        <div class="options" id="option-3">
        </div>
        <div class="options" id="option-4">
        </div>
        <div class="info">
        </div>
        <div class="points">0</div>
        <div class="loader">
          <img src="assets/img/loader.svg" alt="">
        </div>
        <script src="assets/js/jquery.min.js"></script>
        <script src="assets/js/main.js?v=1"></script>
    </body>
</html>